ansible-playbook:
	go run ../../cmd/paasible/. ansible-playbook ./playbook.yml -- -vv -i ./inventory.ini

run:
	go run ../../cmd/paasible/. -c ./paasible.yaml run simple_performance

ui:
	go run ../../cmd/paasible/. serve
