---
- name: Test playbook
  hosts: target
  become: true
  tasks:
    - name: Ensure destination directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
      loop:
        - "{{ destination }}"
